---
communication:
- key: "COMMUNICATION.CREATE"
  description: {}
  resources:
  - "communication"
- key: "COMMUNICATION.DELETE"
  description: {}
  resources:
  - "communication"
  - "id"
- key: "COMMUNICATION.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "COMMUNICATION.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "COMMUNICATION.PROFILE.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "COMMUNICATION.TENANT.CREATE"
  description: {}
  resources:
  - "tenant"
- key: "COMMUNICATION.TENANT.DELETE"
  description: {}
  resources:
  - "tenantKey"
- key: "COMMUNICATION.TENANT.GET_LIST"
  description: {}
  resources: []
- key: "COMMUNICATION.TENANT.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "COMMUNICATION.TENANT.UPDATE"
  description: {}
  resources:
  - "state"
  - "tenant"
- key: "COMMUNICATION.UPDATE"
  description: {}
  resources:
  - "communication"
  - "newBalance"
  - "id"
- key: "METRIC.CREATE"
  description: {}
  resources:
  - "metric"
- key: "METRIC.DELETE"
  description: {}
  resources:
  - "metric"
  - "id"
- key: "METRIC.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "METRIC.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "METRIC.UPDATE"
  description: {}
  resources:
  - "metric"
  - "id"
  - "newMetric"
- key: "POCKET.CREATE"
  description: {}
  resources:
  - "pocket"
- key: "POCKET.DELETE"
  description: {}
  resources:
  - "id"
  - "pocket"
- key: "POCKET.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "POCKET.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "POCKET.UPDATE"
  description: {}
  resources:
  - "newPocket"
  - "id"
  - "pocket"
config:
- key: "CONFIG.ADMIN.CREATE"
  description: {}
  resources:
  - "request"
  - "content"
- key: "CONFIG.ADMIN.CREATE.LIST"
  description: {}
  resources:
  - "files"
  - "tenant"
- key: "CONFIG.ADMIN.DELETE"
  description: {}
  resources:
  - "request"
- key: "CONFIG.ADMIN.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "CONFIG.ADMIN.REFRESH"
  description: {}
  resources:
  - "request"
- key: "CONFIG.ADMIN.UPDATE"
  description: {}
  resources:
  - "request"
  - "content"
- key: "CONFIG.CLIENT.CREATE"
  description: {}
  resources:
  - "request"
  - "content"
- key: "CONFIG.CLIENT.DELETE"
  description: {}
  resources:
  - "request"
- key: "CONFIG.CLIENT.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "CONFIG.CLIENT.UPDATE"
  description: {}
  resources:
  - "request"
  - "content"
- key: "CONFIG.PROFILE_INFO.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "CONFIG.TENANT.CREATE"
  description: {}
  resources:
  - "tenant"
- key: "CONFIG.TENANT.DELETE"
  description: {}
  resources:
  - "tenantKey"
  - "serviceName"
- key: "CONFIG.TENANT.GET_LIST"
  description: {}
  resources:
  - "returnObject"
  - "log"
- key: "CONFIG.TENANT.UPDATE"
  description: {}
  resources:
  - "tenantKey"
  - "serviceName"
  - "tenantState"
uaa:
- key: "ACCOUNT.ACTIVATE"
  description: {}
  resources: []
- key: "ACCOUNT.CHECK_AUTH"
  description: {}
  resources:
  - "request"
- key: "ACCOUNT.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "ACCOUNT.LOGIN.UPDATE"
  description: {}
  resources:
  - "newUser"
  - "id"
  - "user"
- key: "ACCOUNT.PASSWORD.RESET"
  description: {}
  resources:
  - "mail"
- key: "ACCOUNT.PASSWORD.RESET.CHECK"
  description: {}
  resources: []
- key: "ACCOUNT.PASSWORD.RESET.FINISH"
  description: {}
  resources:
  - "keyAndPassword"
- key: "ACCOUNT.PASSWORD.UPDATE"
  description: {}
  resources:
  - "password"
- key: "ACCOUNT.REGISTER"
  description: {}
  resources:
  - "request"
  - "user"
- key: "ACCOUNT.RESET_ACTIVATION"
  description: {}
  resources:
  - "login"
- key: "ACCOUNT.TFA.AVAILABLE_OTP_CHANNEL_SPECS"
  description: {}
  resources: []
- key: "ACCOUNT.TFA.DISABLE"
  description: {}
  resources: []
- key: "ACCOUNT.TFA.ENABLE"
  description: {}
  resources: []
- key: "ACCOUNT.UPDATE"
  description: {}
  resources:
  - "user"
- key: "AUDIT.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "AUDIT.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "CAPTCHA.GET"
  description: {}
  resources:
  - "request"
- key: "CLIENT.CREATE"
  description: {}
  resources:
  - "client"
- key: "CLIENT.DELETE"
  description: {}
  resources:
  - "client"
  - "id"
- key: "CLIENT.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "CLIENT.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "CLIENT.UPDATE"
  description: {}
  resources:
  - "newClient"
  - "client"
  - "id"
- key: "ROLE.CREATE"
  description: {}
  resources:
  - "role"
- key: "ROLE.DELETE"
  description: {}
  resources:
  - "roleKey"
- key: "ROLE.GET_LIST"
  description: {}
  resources:
  - "returnObject"
  - "log"
- key: "ROLE.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "ROLE.MATRIX.GET"
  description: {}
  resources:
  - "returnObject"
- key: "ROLE.MATRIX.UPDATE"
  description: {}
  resources:
  - "roleMatrix"
- key: "ROLE.UPDATE"
  description: {}
  resources:
  - "role"
- key: "SOCIAL.PROVIDERS.GET_LIST"
  description: {}
  resources: []
- key: "SOCIAL.SIGN_IN"
  description: {}
  resources: []
- key: "SOCIAL.SIGN_UP"
  description: {}
  resources: []
- key: "TENANT.LOGIN.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "TENANT.LOGIN.UPDATE"
  description: {}
  resources:
  - "loginsYml"
- key: "TENANT.LOGIN.VALIDATE"
  description: {}
  resources: []
- key: "UAA.PROFILE.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "UAA.TENANT.CREATE"
  description: {}
  resources:
  - "tenant"
- key: "UAA.TENANT.DELETE"
  description: {}
  resources:
  - "tenantKey"
- key: "UAA.TENANT.GET_LIST"
  description: {}
  resources: []
- key: "UAA.TENANT.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "UAA.TENANT.PROPERTIES.UPDATE"
  description: {}
  resources:
  - "uaaYml"
- key: "UAA.TENANT.PROPERTIES.VALIDATE"
  description: {}
  resources: []
- key: "UAA.TENANT.UPDATE"
  description: {}
  resources:
  - "tenant"
  - "status"
- key: "USER.CREATE"
  description: {}
  resources:
  - "user"
- key: "USER.DELETE"
  description: {}
  resources:
  - "id"
  - "user"
- key: "USER.GET_LIST"
  description: {}
  resources:
  - "returnObject"
- key: "USER.GET_LIST.ITEM"
  description: {}
  resources:
  - "returnObject"
- key: "USER.GET_USER_BY_LOGIN"
  description: {}
  resources:
  - "returnObject"
- key: "USER.LOGIN.UPDATE"
  description: {}
  resources:
  - "newUser"
  - "id"
  - "user"
- key: "USER.METRIC.ONLINE"
  description: {}
  resources: []
- key: "USER.TFA.AVAILABLE_OTP_CHANNEL_SPECS"
  description: {}
  resources: []
- key: "USER.TFA.DISABLE"
  description: {}
  resources:
  - "id"
  - "user"
- key: "USER.TFA.ENABLE"
  description: {}
  resources:
  - "id"
  - "user"
- key: "USER.UPDATE"
  description: {}
  resources:
  - "newUser"
  - "id"
  - "user"
