---
communication:
  ROLE_VIEW:
  - privilegeKey: "COMMUNICATION.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.GET_LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.PROFILE.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.TENANT.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.TENANT.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.TENANT.GET_LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.TENANT.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.TENANT.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "COMMUNICATION.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "METRIC.CREATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "METRIC.DELETE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "METRIC.GET_LIST.ITEM"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "METRIC.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "POCKET.CREATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "POCKET.DELETE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "POCKET.GET_LIST.ITEM"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "POCKET.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
config:
  ROLE_VIEW:
  - privilegeKey: "CONFIG.ADMIN.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.ADMIN.CREATE.LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.ADMIN.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.ADMIN.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.ADMIN.REFRESH"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.ADMIN.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.CLIENT.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.CLIENT.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.CLIENT.GET_LIST.ITEM"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.CLIENT.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.PROFILE_INFO.GET_LIST.ITEM"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.TENANT.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.TENANT.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.TENANT.GET_LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CONFIG.TENANT.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
uaa:
  ROLE_VIEW:
  - privilegeKey: "ACCOUNT.ACTIVATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.CHECK_AUTH"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.GET_LIST.ITEM"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.LOGIN.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.PASSWORD.RESET"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.PASSWORD.RESET.CHECK"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.PASSWORD.RESET.FINISH"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.PASSWORD.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.REGISTER"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.RESET_ACTIVATION"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.TFA.AVAILABLE_OTP_CHANNEL_SPECS"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.TFA.DISABLE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.TFA.ENABLE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ACCOUNT.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "AUDIT.GET_LIST"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "AUDIT.GET_LIST.ITEM"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CAPTCHA.GET"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CLIENT.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CLIENT.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CLIENT.GET_LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CLIENT.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "CLIENT.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.GET_LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.MATRIX.GET"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.MATRIX.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "ROLE.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "SOCIAL.PROVIDERS.GET_LIST"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "SOCIAL.SIGN_IN"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "SOCIAL.SIGN_UP"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "TENANT.LOGIN.GET_LIST"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "TENANT.LOGIN.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "TENANT.LOGIN.VALIDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.PROFILE.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.DELETE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.GET_LIST"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.PROPERTIES.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.PROPERTIES.VALIDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "UAA.TENANT.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.CREATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.DELETE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.GET_LIST"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.GET_LIST.ITEM"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.GET_USER_BY_LOGIN"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.LOGIN.UPDATE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.METRIC.ONLINE"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.TFA.AVAILABLE_OTP_CHANNEL_SPECS"
    disabled: true
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.TFA.DISABLE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.TFA.ENABLE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
  - privilegeKey: "USER.UPDATE"
    disabled: false
    deleted: false
    envCondition: null
    resourceCondition: null
    reactionStrategy: null
